### ISSUE TITLE
Propose rewrite in C using librubberband and pulse/simple.h

### ISSUE THREAD

**Issue by charpointer** [charpointer/lyrebird#38]
While researching into methods to perform formant shifting in Python, it has come to my attention that this may not be possible without having significant latency, or writing a `libpulse` wrapper. I am proposing the idea that we begin a rewrite of v1.2/v1.3/[insert current version number] of Lyrebird purely in C. This would mean no Python interpretor required, faster startup times, less latency (since we would **directly** be using PulseAudio) and would most important allow us direct and unrestricted access to PulseAudio under the hood.

Alternatively, we could write a `ctypes` wrapper over everything or even go so far as to write a Python extension in C, but I'm proposing a rewrite for the reasons above. If we were to go through with the rewrite, it will be done in a parallel branch to `master`.

I've attached some below links to documentation about the PulseAudio library for C.
https://gavv.github.io/articles/pulseaudio-under-the-hood/
https://acassis.wordpress.com/2012/10/04/reading-microphone-audio-using-pulseaudio-simple/

**Comment by harrego** [comment]
It has always been my dream to fork Lyrebird for myself and rewrite it all in C.

**Comment by aspenluxxxy** [comment]
i'd love to shill rust but C's prolly better for stuff like this

**Comment by harrego** [comment]
@chxrlt No longer C?

**Comment by harrego** [comment]
This has now happened at a prototype stage in branch `c`, future discussion should be in a new thread
