### ISSUE TITLE
Compatibility with PipeWire

### ISSUE THREAD

**Issue by MisterDA** [charpointer/lyrebird#54]
[PipeWire][] is a new Linux multimedia framework aimed at replacing PulseAudio, Jack, with Alsa compatibility. I provides integration with existing applications with compatible libraries and protocol.
The `pacmd` is however PulseAudio-only and isn't available on some distributions as it's delivered with the PulseAudio package which conflicts with PipeWire.
Could the dependency to `pacmd` be dropped or an alternative be found? for instance, direct calls to the PulseAudio library/daemon?
```
Traceback (most recent call last):
  File "/usr/share/lyrebird/app.py", line 13, in <module>
    win = mainwindow.MainWindow()
  File "/usr/share/lyrebird/app/mainwindow.py", line 62, in __init__
    utils.unload_pa_modules(check_state=False)
  File "/usr/share/lyrebird/app/core/utils.py", line 60, in unload_pa_modules
    subprocess.call('pacmd unload-module module-null-sink'.split(" "))
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pacmd'
```
[PipeWire]: https://pipewire.org/

**Comment by Tkd-Alex** [comment]
Same for me :cry:

**Comment by harrego** [comment]
This is being discussed in #62. I'm not at all opposed to the idea but it is not a priority right now. As mentioned in the previous issue I will look into the idea after v2 is complete.
