### ISSUE TITLE
[Question] How can I create custom voices?

### ISSUE THREAD

**Issue by Toadfield** [charpointer/lyrebird#55]
I wanna create a custom voice.

**Comment by harrego** [comment]
There is a tutorial on the [README](https://github.com/charpointer/lyrebird#editing-presets), I've linked the specific section.

**Comment by Toadfield** [comment]
Then I would like it,if there would be a gui way to do that.

**Comment by charpointer** [comment]
currently this is not implemented, and will *not* be implemented in the current python branch, however we will consider it later down the road when we have rewritten lyrebird in C (it's an ongoing effort).
