### ISSUE TITLE
Use pkg-config to set cflags

### ISSUE THREAD

**Issue by aurium** [charpointer/lyrebird#65]
Today CFLAGS var on Makefile is hardcoded:
```CFLAGS = -g -Wall -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_REENTRANT```
However, in my system, my glib-2.0 includes are in `/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include`.

```pkg-config --libs glib-2.0``` can resolve this issue.

**Comment by harrego** [comment]
Would you mind putting in a pull request fixing this or giving an example?

For the first few commits `pkg-config` was used in the Makefile but CFLAGS would never end up in the final gcc command, instead I would just see a double space where it should be with no variable in the middle. I could never figure out why and in the end gave up and just hardcoded the libraries. [This is the code in question.](https://github.com/charpointer/lyrebird/blob/72c2d1282a71dd33ceadbff44397c51788e0632f/Makefile)

**Comment by harrego** [comment]
Fixed with #66
